### ISSUE TITLE
Preprocessors, macros, etc. not highlighted

### ISSUE THREAD

**Issue by mandeep** [petervaro/C11#5]
Pretty much any syntax that begins with a # is not highlighted. #include, #ifdef, #define, etc.

**Comment by petervaro** [comment]
Did you look at the README's screenshot? That will give you a rough idea on what to expect I guess :smile: All of the preprocessor directives are working and highlighted.

**Comment by mandeep** [comment]
Yes, I looked at the screenshot and the same problem exists there. The preprocessors use whatever the color scheme uses for syntax it doesn't recognize. As an example, look how the built-in Monokai color scheme handles the directives.

**Comment by petervaro** [comment]
On the screenshot it is not using the *unrecognised* or *invalid* color. It is using the proper highlighter class. But if you don't believe me, then look at [the code](https://github.com/petervaro/C11/blob/master/C11.py#L446). Anyway, can you show me two side-by-side screenshots, on what you have, instead of what you are expecting?

**Comment by mandeep** [comment]
The first image is a screenshot of the C11 syntax. The second image is a screenshot of the C syntax. I expected preprocessor directives to be highlighted the same way builtins are highlighted like they are in the second image. 

![screenshot from 2017-09-08 11-42-30](https://user-images.githubusercontent.com/10521687/30221976-062f7d8a-948b-11e7-9556-935fb0a4fd96.png)
![screenshot from 2017-09-08 11-42-04](https://user-images.githubusercontent.com/10521687/30221989-0e20acf8-948b-11e7-81c7-07261d00b572.png)

**Comment by petervaro** [comment]
Well, it looks like, that the problem is with your colour theme, as it clearly does not specify the `meta.other.macro` highlighter class :slightly_frowning_face:

**Comment by mandeep** [comment]
The highlighting will be the same no matter the color scheme. Can you give me an example of a color scheme that highlights correctly?

**Comment by petervaro** [comment]
It looks like, none of the built-in one :slightly_frowning_face: are defining such highlighter class. But all my third party themes and of course my own one are doing it. (I tried the ones that are coming with `Babel` and `JavaScript Ultimate` and mine which is coming with `Python 3`)

**Comment by mandeep** [comment]
Thanks for looking into this. I'll open an issue on the theme I'm using for the meta.other.macro class.
